# help
help:
  shortcut: h
  variants:
    help_all:
      description: Get server commands list
      usage: help
    help_one:
      description: Get server command help
      usage: help <command>
# kill
kill:
  shortcut: k
  variants:
    kill_me:
      description: Kill yourself
      usage: kill
    kill_player:
      description: Kill a player
      usage: kill <player>
